#!/bin/sh

## source env
. ./.env.prod
## deploy env
fly secrets set \
	PHX_HOST="$PHX_HOST" \
	DIMONA_API_KEY="$DIMONA_API_KEY" \
	AWS_ACCESS_KEY_ID_PLAZA="$AWS_ACCESS_KEY_ID_PLAZA" \
	AWS_SECRET_ACCESS_KEY_PLAZA="$AWS_SECRET_ACCESS_KEY_PLAZA" \
	STRIPE_API_KEY="$STRIPE_API_KEY" \
	STRIPE_WEBHOOK_SIGNING_SECRET="$STRIPE_WEBHOOK_SIGNING_SECRET" \
	POSTMARK_API_KEY="$POSTMARK_API_KEY"
